name: fabric_etl_project
version: 1.0.0
config-version: 2
profile: fabric_etl_project

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  fabric_etl_project:
    +file_format: delta
    bronze:
      +materialized: view
    silver:
      +materialized: incremental
      +incremental_strategy: merge
      +on_schema_change: sync_all_columns
    gold:
      +materialized: table
